services:
  backend:
    build:
      context: .
    image: digitalterrainhub:v1.0
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - nodeodm
      - postgres
    env_file:
      - ./backend/.env

  nodeodm:
    image: opendronemap/nodeodm
    ports:
      - "3000:3000"

  postgres:
    image: postgis/postgis:15-3.5
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
