services:
  app:
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - nodeodm
      - postgres

  nodeodm:
    image: opendronemap/nodeodm
    ports:
      - 3000:3000

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      PG_DB: mydb
      PG_USER: user
      PG_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: