services:
  backend:
    build:
      context: ./backend
    image: digitalterrainhub:v1.0
    ports:
      - "8000:8000"
    volumes:
      - ./backend/Config:/app/Config
      - ./backend/Core:/app/Core
      - ./backend/MapViewer:/app/MapViewer
      - ./backend/Payment:/app/Payment
      - ./backend/PyODM:/app/PyODM
      - ./backend/User:/app/User
      - odm_tasks_dir:/app/media/tasks
    depends_on:
      - postgres
      # - nodeodm
      # - frontend
    env_file:
      - ./backend/.env
    networks:
      - backend-fronted-network
      - backend-network

  frontend:
    build:
      context: ./frontend
    image: astrotemplatesgenerator
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - backend-fronted-network

  nodeodm:
    image: opendronemap/nodeodm
    ports:
      - "3000:3000"
    volumes:
      - odm_tasks_dir:/var/www/data
    networks:
      - backend-network

  postgres:
    image: postgis/postgis:15-3.5
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  pgdata:
  odm_tasks_dir:

networks:
  backend-network:
    driver: bridge
  backend-fronted-network:
    driver: bridge
