from Config.django.base import MEDIA_ROOT, DATA_UPLOAD_MAX_MEMORY_SIZE

TUS_UPLOAD_DIR = MEDIA_ROOT / 'uploads'
TUS_DESTINATION_DIR  = TUS_UPLOAD_DIR
TUS_FILE_NAME_FORMAT = 'random-suffix'
TUS_EXISTING_FILE = 'overwrite'
TUS_MAX_FILE_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE